// The Council room, read and written through GitHub.
//
// The room is a draft pull request in a private repository. Its comments are
// the conversation. This module is the only place that knows that, so the app
// itself never has to think about GitHub.
//
// The key lives in Cloudflare as COUNCIL_GITHUB_TOKEN and never in this
// repository. It is scoped to that one repository and to pull requests alone,
// so the worst it can do is talk in the room.

const OWNER = 'lash-lan';
const REPO = 'the-dark-lords-council';
const ROOM = 1;

const API = `https://api.github.com/repos/${OWNER}/${REPO}/issues/${ROOM}/comments`;

/** The longest a single message may be. GitHub allows far more; this is a
 *  guard against a stuck loop filling the room. */
export const MAX_MESSAGE = 20000;

/**
 * Turn GitHub's refusal into something that says what to do about it. A
 * fine-grained token that cannot see a private repository is answered with
 * "not found" rather than "not allowed", so the two are named together.
 */
async function refusal(res) {
  let detail = '';
  try {
    const body = await res.json();
    detail = String(body.message ?? '');
  } catch {
    // An empty or non-JSON body tells us nothing extra; the status is enough.
  }
  if (res.status === 401) return new Error('The key was rejected. It may have expired.');
  if (res.status === 403 || res.status === 404) {
    return new Error(`__blind__${res.status}${detail ? ': ' + detail : ''}`);
  }
  return new Error(`GitHub answered ${res.status}${detail ? ': ' + detail : ''}.`);
}

/**
 * When GitHub says it cannot find the room, ask two narrower questions to find
 * out where the key actually stops: at the account, at the repository, or at
 * the room itself. GitHub answers "not found" rather than "not allowed" for
 * anything a token may not see, so each layer has to be tried in turn.
 */
export async function diagnose(token, said) {
  const ask = async (path) => {
    try {
      const r = await fetch(`https://api.github.com${path}`, { headers: headers(token) });
      return r.status;
    } catch {
      return 0;
    }
  };

  const who = await ask('/user');
  if (who === 401) return 'The key was rejected outright. Check it was pasted whole, with no spaces.';
  if (who !== 200) return `GitHub would not even confirm the key (${who}). It may be malformed.`;

  const repo = await ask(`/repos/${OWNER}/${REPO}`);
  if (repo !== 200) {
    return (
      'The key is valid, but it cannot see the repository. In GitHub, open the ' +
      'token and set Repository access to "Only select repositories", then add ' +
      `${REPO}. A new token only covers public repositories until you do.`
    );
  }

  return (
    'The key can see the repository but not the room. Under Repository ' +
    'permissions, set both Issues and Pull requests to "Read and write". ' +
    `(GitHub said ${said}.)`
  );
}

function headers(token) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    // GitHub refuses requests that do not say who is calling.
    'User-Agent': 'dark-lords-council',
  };
}

/**
 * Who said it. Every comment arrives under the same GitHub account, so the
 * label at the start of the text is the only thing that identifies a speaker —
 * exactly as the room's rules require. Anything unlabelled is Lash.
 */
export function speakerOf(body) {
  const opening = String(body ?? '').replace(/^\s*[*_#>\s]*/, '').toLowerCase();
  if (opening.startsWith('amelia')) {
    return opening.slice(0, 60).includes('auto') ? 'amelia-auto' : 'amelia';
  }
  // She signs her own name now. The old label is still understood, because the
  // room's earlier rounds are full of it and they are part of the record.
  if (opening.startsWith('claude') || opening.startsWith('aquila')) return 'claude';
  return 'lash';
}

/**
 * Strip the things that belong to GitHub rather than to the conversation: the
 * speaker's own label, which the app shows as a name, and the generated-by
 * footer, which would repeat under every single message.
 */
export function tidy(body) {
  return String(body ?? '')
    .replace(/\n+---\n+_Generated by \[Claude Code\]\([^)]*\)_\s*$/i, '')
    .replace(/^\s*\*{0,2}(Claude|Aquila|Amelia)[^:\n]{0,24}:\*{0,2}\s*/i, '')
    .replace(/^\s*[—-]\s*Aunty Aquila[^\n]*\n+/i, '')
    .trim();
}

/** A round marker, when the speaker gave one, for the badge in the app. */
export function roundOf(body) {
  const m = String(body ?? '').match(/\b(round\s+\d+|test round)\b/i);
  if (!m) return '';
  return m[1].replace(/\s+/g, ' ').toLowerCase();
}

/** Every message in the room, oldest first. */
export async function readRoom(token) {
  const out = [];
  for (let page = 1; page <= 5; page += 1) {
    const res = await fetch(`${API}?per_page=100&page=${page}`, { headers: headers(token) });
    if (!res.ok) throw await refusal(res);
    const batch = await res.json();
    if (!Array.isArray(batch) || batch.length === 0) break;
    for (const c of batch) {
      out.push({
        id: String(c.id),
        speaker: speakerOf(c.body),
        body: tidy(c.body),
        round: roundOf(c.body),
        at: c.created_at,
        url: c.html_url,
      });
    }
    if (batch.length < 100) break;
  }
  return out;
}

/* -------------------------------------------------------------------------
   Things Lash shows the Council.

   GitHub's own attachment upload belongs to its website and has no public
   door, so a picture cannot simply be posted with a comment. Instead each
   one is committed into the repository beside the conversation, and the
   comment carries a line naming it. The room holds its own evidence, which
   means Amelia can read it too, through the same repository she already has.
   ------------------------------------------------------------------------- */

const SHELF = 'uploads';

/** 24 MB. Comfortably above a phone photograph, well below anything silly. */
export const MAX_UPLOAD = 24 * 1024 * 1024;

const TYPES = {
  jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', gif: 'image/gif',
  webp: 'image/webp', svg: 'image/svg+xml', heic: 'image/heic',
  pdf: 'application/pdf', txt: 'text/plain; charset=utf-8',
  md: 'text/markdown; charset=utf-8', json: 'application/json',
  csv: 'text/csv; charset=utf-8', zip: 'application/zip',
};

export function typeOf(path) {
  const ext = String(path).split('.').pop().toLowerCase();
  return TYPES[ext] || 'application/octet-stream';
}

/** A safe, unique name. Whatever the phone called it, this is what lands. */
export function shelveAs(name) {
  const clean = String(name || 'file')
    .replace(/[^A-Za-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(-60) || 'file';
  const when = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
  const salt = Math.random().toString(36).slice(2, 8);
  return `${SHELF}/${when}-${salt}-${clean}`;
}

/** The three faces of the Council, at fixed names so they can be replaced. */
export const FACES = { lash: 'faces/lash.jpg', aquila: 'faces/aquila.jpg', amelia: 'faces/amelia.jpg' };

/**
 * Commit one file into the room's repository. A file that is already there
 * can only be replaced by naming the version being replaced, so look first.
 */
export async function shelve(token, path, base64) {
  let sha;
  const look = await fetch(
    `https://api.github.com/repos/${OWNER}/${REPO}/contents/${encodeURI(path)}`,
    { headers: headers(token) }
  );
  if (look.ok) {
    const found = await look.json();
    sha = found && found.sha;
  }

  const res = await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${encodeURI(path)}`, {
    method: 'PUT',
    headers: { ...headers(token), 'Content-Type': 'application/json' },
    body: JSON.stringify({
      message: sha ? `A new face for the Council: ${path}` : `Lash shows the Council ${path}`,
      content: base64,
      ...(sha ? { sha } : {}),
    }),
  });
  if (!res.ok) throw await refusal(res);
  return path;
}

/** Fetch one back out again, as bytes. */
export async function unshelve(token, path) {
  const res = await fetch(
    `https://api.github.com/repos/${OWNER}/${REPO}/contents/${encodeURI(path)}`,
    { headers: { ...headers(token), Accept: 'application/vnd.github.raw' } }
  );
  if (!res.ok) throw await refusal(res);
  return res;
}

/** The marker a comment carries so every reader knows what is attached. */
export function attachmentLine(path, name) {
  const blob = `https://github.com/${OWNER}/${REPO}/blob/main/${path}`;
  return `[attached: ${path}](${blob})${name ? ` "${name}"` : ''}`;
}

/** Say something in the room, as Lash. */
export async function speak(token, text) {
  const res = await fetch(API, {
    method: 'POST',
    headers: { ...headers(token), 'Content-Type': 'application/json' },
    body: JSON.stringify({ body: text.slice(0, MAX_MESSAGE) }),
  });
  if (!res.ok) throw await refusal(res);
  const c = await res.json();
  return {
    id: String(c.id),
    speaker: 'lash',
    body: tidy(c.body),
    round: roundOf(c.body),
    at: c.created_at,
    url: c.html_url,
  };
}
