// The Council room, read and written through GitHub.
//
// The room is a draft pull request in a private repository. Its comments are
// the conversation. This module is the only place that knows that, so the app
// itself never has to think about GitHub.
//
// The key lives in Cloudflare as COUNCIL_GITHUB_TOKEN and never in this
// repository. It is scoped to that one repository and to pull requests alone,
// so the worst it can do is talk in the room.

const OWNER = 'lash-lan';
const REPO = 'the-dark-lords-council';
const ROOM = 1;

const API = `https://api.github.com/repos/${OWNER}/${REPO}/issues/${ROOM}/comments`;

/** The longest a single message may be. GitHub allows far more; this is a
 *  guard against a stuck loop filling the room. */
export const MAX_MESSAGE = 20000;

function headers(token) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    // GitHub refuses requests that do not say who is calling.
    'User-Agent': 'dark-lords-council',
  };
}

/**
 * Who said it. Every comment arrives under the same GitHub account, so the
 * label at the start of the text is the only thing that identifies a speaker —
 * exactly as the room's rules require. Anything unlabelled is Lash.
 */
export function speakerOf(body) {
  const opening = String(body ?? '').replace(/^\s*[*_#>\s]*/, '').toLowerCase();
  if (opening.startsWith('amelia')) {
    return opening.slice(0, 60).includes('auto') ? 'amelia-auto' : 'amelia';
  }
  if (opening.startsWith('claude')) return 'claude';
  return 'lash';
}

/**
 * Strip the things that belong to GitHub rather than to the conversation: the
 * speaker's own label, which the app shows as a name, and the generated-by
 * footer, which would repeat under every single message.
 */
export function tidy(body) {
  return String(body ?? '')
    .replace(/\n+---\n+_Generated by \[Claude Code\]\([^)]*\)_\s*$/i, '')
    .replace(/^\s*\*{0,2}(Claude|Amelia)[^:\n]{0,24}:\*{0,2}\s*/i, '')
    .trim();
}

/** A round marker, when the speaker gave one, for the badge in the app. */
export function roundOf(body) {
  const m = String(body ?? '').match(/\b(round\s+\d+|test round)\b/i);
  if (!m) return '';
  return m[1].replace(/\s+/g, ' ').toLowerCase();
}

/** Every message in the room, oldest first. */
export async function readRoom(token) {
  const out = [];
  for (let page = 1; page <= 5; page += 1) {
    const res = await fetch(`${API}?per_page=100&page=${page}`, { headers: headers(token) });
    if (!res.ok) {
      throw new Error(res.status === 401 || res.status === 403 ? 'key' : 'github');
    }
    const batch = await res.json();
    if (!Array.isArray(batch) || batch.length === 0) break;
    for (const c of batch) {
      out.push({
        id: String(c.id),
        speaker: speakerOf(c.body),
        body: tidy(c.body),
        round: roundOf(c.body),
        at: c.created_at,
        url: c.html_url,
      });
    }
    if (batch.length < 100) break;
  }
  return out;
}

/** Say something in the room, as Lash. */
export async function speak(token, text) {
  const res = await fetch(API, {
    method: 'POST',
    headers: { ...headers(token), 'Content-Type': 'application/json' },
    body: JSON.stringify({ body: text.slice(0, MAX_MESSAGE) }),
  });
  if (!res.ok) {
    throw new Error(res.status === 401 || res.status === 403 ? 'key' : 'github');
  }
  const c = await res.json();
  return {
    id: String(c.id),
    speaker: 'lash',
    body: tidy(c.body),
    round: roundOf(c.body),
    at: c.created_at,
    url: c.html_url,
  };
}
